name: Run cookiecutter on first push

on: [push]

jobs:
  run-cookiecutter:
    if: ${{ github.repository != 'sed-cloud/service-gh-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install cookiecutter
        run: pip3 install cookiecutter

      - uses: actions/github-script@v4
        id: fetch-repo-and-user-details
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name) {
                name
                description
                owner {
                  login
                  ... on User {
                    name
                  }
                  ... on Organization {
                    name
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            console.log(result)
            return result
      - name: Rebuild contents using cookiecutter
        shell: bash
        env:
          INFO: ${{ steps.fetch-repo-and-user-details.outputs.result }}
          GH_PAT: ${{ secrets.GH_PAT }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          # Delete this workflow:
          rm -rf .github
          export REPO_NAME=$(echo $INFO | jq -r '.repository.name')
          
          # Run cookiecutter
          cookiecutter gh:sed-cloud/service-template --no-input \
            package_name=$REPO_NAME
          
          # Move generated content to root directory of repo
          mv $REPO_NAME/$REPO_NAME $REPO_NAME/src
          cd $REPO_NAME
          mv -v ./* ..
          cd ..
          
          mv $REPO_NAME/.gitignore .gitignore 
          mv $REPO_NAME/.pre-commit.yaml .pre-commit.yaml 
          mkdir .github/
          mkdir .github/rename/
          mv $REPO_NAME/.github/workflows/* .github/rename/
          
          rm -rf $REPO_NAME/
          mv src/ $REPO_NAME/
          
      - name: Force push new repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initial Commit"
          push_options: --force
